stages:
  - build
  - release

build-mac:
  stage: build
  tags:
    - macos
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npm ci
    - npm run electron:build:mac
  artifacts:
    paths:
      - release/
    expire_in: 1 week

build-win:
  stage: build 
  tags:
    - docker
  image: electronuserland/builder:wine
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run electron:build:win
  artifacts:
    paths:
      - release/
    expire_in: 1 week

build-linux:
  stage: build
  tags:
    - docker
  image: electronuserland/builder:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run electron:build:linux
  artifacts:
    paths:
      - release/
    expire_in: 1 week

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build-win
    - build-linux
    - build-mac
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Release $CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: "Windows"
          url: "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/download?job=build-win"
        - name: "Linux"
          url: "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/download?job=build-linux"
        - name: "macOS"
          url: "$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_TAG/download?job=build-mac"